//
//  StructuredOutput.swift
//  LangTools
//
//  Created by Reid Chatham on 1/26/25.
//

import Foundation

// MARK: - StructuredOutput Protocol

/// Protocol for types that can be used as structured LLM responses.
/// Conformance can be generated by the @StructuredOutput macro.
public protocol StructuredOutput: Codable, Sendable {
    /// JSON Schema representation of the type
    static var jsonSchema: JSONSchema { get }
}

// MARK: - JSONSchema

/// Type-safe JSON Schema representation for structured output.
/// Follows the JSON Schema specification used by LLM providers.
/// Uses indirect storage for recursive properties to avoid Swift's value type recursion limitation.
public indirect enum JSONSchema: Codable, Sendable, Equatable {
    case schema(JSONSchemaDefinition)

    /// The underlying schema definition
    public var definition: JSONSchemaDefinition {
        switch self {
        case .schema(let def): return def
        }
    }

    // Forward common properties
    public var type: SchemaType { definition.type }
    public var properties: [String: JSONSchema]? { definition.properties }
    public var required: [String]? { definition.required }
    public var additionalProperties: Bool? { definition.additionalProperties }
    public var items: JSONSchema? { definition.items }
    public var enumValues: [String]? { definition.enumValues }
    public var schemaDescription: String? { definition.schemaDescription }
    public var title: String? { definition.title }

    /// Schema type enumeration
    public enum SchemaType: String, Codable, Sendable {
        case object
        case array
        case string
        case number
        case integer
        case boolean
        case null
    }

    /// Creates a JSONSchema with the specified properties.
    public init(
        type: SchemaType,
        properties: [String: JSONSchema]? = nil,
        required: [String]? = nil,
        additionalProperties: Bool? = nil,
        items: JSONSchema? = nil,
        enumValues: [String]? = nil,
        description: String? = nil,
        title: String? = nil
    ) {
        self = .schema(JSONSchemaDefinition(
            type: type,
            properties: properties,
            required: required,
            additionalProperties: additionalProperties,
            items: items,
            enumValues: enumValues,
            schemaDescription: description,
            title: title
        ))
    }

    // MARK: - Codable

    public init(from decoder: Decoder) throws {
        let definition = try JSONSchemaDefinition(from: decoder)
        self = .schema(definition)
    }

    public func encode(to encoder: Encoder) throws {
        try definition.encode(to: encoder)
    }

    // MARK: - Factory Methods

    /// Creates a string schema
    public static func string(description: String? = nil, enumValues: [String]? = nil) -> JSONSchema {
        JSONSchema(type: .string, enumValues: enumValues, description: description)
    }

    /// Creates a number schema
    public static func number(description: String? = nil) -> JSONSchema {
        JSONSchema(type: .number, description: description)
    }

    /// Creates an integer schema
    public static func integer(description: String? = nil) -> JSONSchema {
        JSONSchema(type: .integer, description: description)
    }

    /// Creates a boolean schema
    public static func boolean(description: String? = nil) -> JSONSchema {
        JSONSchema(type: .boolean, description: description)
    }

    /// Creates an array schema
    public static func array(items: JSONSchema, description: String? = nil) -> JSONSchema {
        JSONSchema(type: .array, items: items, description: description)
    }

    /// Creates an object schema
    public static func object(
        properties: [String: JSONSchema],
        required: [String]? = nil,
        additionalProperties: Bool = false,
        description: String? = nil,
        title: String? = nil
    ) -> JSONSchema {
        JSONSchema(
            type: .object,
            properties: properties,
            required: required,
            additionalProperties: additionalProperties,
            description: description,
            title: title
        )
    }

    /// Creates a schema from a StructuredOutput type
    public static func from<T: StructuredOutput>(_ type: T.Type) -> JSONSchema {
        T.jsonSchema
    }
}

/// Internal definition struct for JSONSchema storage
public struct JSONSchemaDefinition: Codable, Sendable, Equatable {
    public let type: JSONSchema.SchemaType
    public let properties: [String: JSONSchema]?
    public let required: [String]?
    public let additionalProperties: Bool?
    public let items: JSONSchema?
    public let enumValues: [String]?
    public let schemaDescription: String?
    public let title: String?

    public init(
        type: JSONSchema.SchemaType,
        properties: [String: JSONSchema]? = nil,
        required: [String]? = nil,
        additionalProperties: Bool? = nil,
        items: JSONSchema? = nil,
        enumValues: [String]? = nil,
        schemaDescription: String? = nil,
        title: String? = nil
    ) {
        self.type = type
        self.properties = properties
        self.required = required
        self.additionalProperties = additionalProperties
        self.items = items
        self.enumValues = enumValues
        self.schemaDescription = schemaDescription
        self.title = title
    }

    // Custom CodingKeys to handle "enum" and "description" keywords
    enum CodingKeys: String, CodingKey {
        case type, properties, required, additionalProperties, items, title
        case enumValues = "enum"
        case schemaDescription = "description"
    }
}

// MARK: - LangToolsStructuredOutputRequest Protocol

/// Protocol for requests that can return structured output.
/// Providers implement this to add structured output support to their requests.
/// Structured output is controlled at runtime via the responseSchema property.
public protocol LangToolsStructuredOutputRequest: LangToolsRequest {
    /// JSON Schema for the expected response structure.
    /// When set, the provider will return structured output matching this schema.
    /// When nil, the provider returns normal text responses.
    var responseSchema: JSONSchema? { get set }
}

extension LangToolsStructuredOutputRequest {
    /// Convenience method to set the response schema from a StructuredOutput type
    public mutating func setResponseType<T: StructuredOutput>(_ type: T.Type) {
        responseSchema = T.jsonSchema
    }
}

// MARK: - LangToolsStructuredOutputResponse Protocol

/// Protocol for responses that can return structured output.
public protocol LangToolsStructuredOutputResponse: LangToolsChatResponse {
    /// The raw JSON string content from the response
    var jsonContent: String? { get }
}

extension LangToolsStructuredOutputResponse {
    /// Decode the response content as the specified structured type
    /// - Parameter type: The StructuredOutput type to decode as
    /// - Returns: Decoded structured response
    public func structuredOutput<T: StructuredOutput>(as type: T.Type) throws -> T {
        guard let jsonString = jsonContent,
              let jsonData = jsonString.data(using: .utf8) else {
            throw StructuredOutputError.invalidResponse("Response does not contain valid JSON content")
        }

        do {
            return try JSONDecoder().decode(T.self, from: jsonData)
        } catch {
            throw StructuredOutputError.decodingFailed(error)
        }
    }

    /// Convenience: Decode the response content, inferring type
    public func structuredOutput<T: StructuredOutput>() throws -> T {
        try structuredOutput(as: T.self)
    }
}

// MARK: - NoStructuredOutput

/// Placeholder type for requests that don't use structured output
public struct NoStructuredOutput: StructuredOutput {
    public static var jsonSchema: JSONSchema {
        .object(properties: [:])
    }

    public init() {}
}

// MARK: - StructuredOutputError

/// Errors related to structured output processing
public enum StructuredOutputError: Error, LocalizedError {
    case invalidResponse(String)
    case decodingFailed(Error)
    case modelDoesNotSupportStructuredOutput(model: String, supportedModels: [String])
    case schemaRequired

    public var errorDescription: String? {
        switch self {
        case .invalidResponse(let message):
            return "Invalid structured response: \(message)"
        case .decodingFailed(let error):
            return "Failed to decode structured response: \(error.localizedDescription)"
        case .modelDoesNotSupportStructuredOutput(let model, let supportedModels):
            return "Model '\(model)' does not support structured output. Supported models: \(supportedModels.joined(separator: ", "))"
        case .schemaRequired:
            return "Response schema is required for structured output requests"
        }
    }
}

// MARK: - JSONSchema CustomStringConvertible

extension JSONSchema: CustomStringConvertible {
    public var description: String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        guard let data = try? encoder.encode(self),
              let string = String(data: data, encoding: .utf8) else {
            return "JSONSchema(type: \(type.rawValue))"
        }
        return string
    }
}
