//
//  StructuredOutput.swift
//  LangTools
//
//  Created by Reid Chatham on 1/26/25.
//

import Foundation
import JSON

// MARK: - StructuredOutput Protocol

/// Protocol for types that can be used as structured LLM responses.
///
/// `StructuredOutput` refines `JSONConvertible` (from the JSON package) with
/// convenience initialisers for decoding from raw JSON strings and data,
/// plus schema-validated decoding helpers.
///
/// Conformance can be generated by the `@JSONSchema` macro.
public protocol StructuredOutput: JSONConvertible {}

// MARK: - StructuredOutput Initializers

extension StructuredOutput {
    /// Decode a StructuredOutput value from raw JSON data.
    public init(jsonData: Data) throws {
        do {
            self = try JSONDecoder().decode(Self.self, from: jsonData)
        } catch {
            throw StructuredOutputError.decodingFailed(error)
        }
    }

    /// Decode a StructuredOutput value from a JSON string.
    public init(jsonString: String) throws {
        guard let data = jsonString.data(using: .utf8) else {
            throw StructuredOutputError.invalidResponse("Unable to convert string to UTF-8 data")
        }
        try self.init(jsonData: data)
    }

    /// Decode a StructuredOutput value from a `JSON` value.
    public init(json: JSON) throws {
        let data = try JSONEncoder().encode(json)
        try self.init(jsonData: data)
    }

    /// Validate a `JSON` value against this type's schema, then decode it.
    public static func validated(from json: JSON) throws -> Self {
        try json.validate(against: Self.jsonSchema)
        return try Self.init(json: json)
    }

    /// Validate raw JSON data against this type's schema, then decode it.
    public static func validated(from data: Data) throws -> Self {
        let json = try JSON(data: data)
        return try validated(from: json)
    }
}

// MARK: - LangToolsStructuredOutputRequest Protocol

/// Protocol for requests that can return structured output.
/// Providers implement this to add structured output support to their requests.
/// Structured output is controlled at runtime via the responseSchema property.
public protocol LangToolsStructuredOutputRequest: LangToolsRequest where Response: LangToolsStructuredOutputResponse {
    /// JSON Schema for the expected response structure.
    /// When set, the provider will return structured output matching this schema.
    /// When nil, the provider returns normal text responses.
    var responseSchema: JSONSchema? { get set }
}

extension LangToolsStructuredOutputRequest {
    /// Convenience method to set the response schema from a StructuredOutput type
    public mutating func setResponseType<T: StructuredOutput>(_ type: T.Type) {
        responseSchema = T.jsonSchema
    }
}

// MARK: - LangToolsStructuredOutputResponse Protocol

/// Protocol for responses that can return structured output.
public protocol LangToolsStructuredOutputResponse: LangToolsChatResponse {
    /// The raw JSON string content from the response
    var jsonContent: String? { get }
}

extension LangToolsStructuredOutputResponse {
    /// Decode the response content as the specified structured type
    /// - Parameter type: The StructuredOutput type to decode as
    /// - Returns: Decoded structured response
    public func structuredOutput<T: StructuredOutput>(as type: T.Type) throws -> T {
        guard let jsonString = jsonContent else {
            throw StructuredOutputError.invalidResponse("Response does not contain valid JSON content")
        }
        return try T(jsonString: jsonString)
    }

    /// Convenience: Decode the response content, inferring type
    public func structuredOutput<T: StructuredOutput>() throws -> T {
        try structuredOutput(as: T.self)
    }
}

// MARK: - NoStructuredOutput

/// Sentinel type for requests that don't use structured output.
///
/// This is a placeholder — not intended for direct use as a response type.
/// It exists so that generic code can have a default `StructuredOutput` type
/// without requiring callers to specify one.
public struct NoStructuredOutput: StructuredOutput {
    public static var jsonSchema: JSONSchema {
        .object()
    }

    public init() {}
}

// MARK: - StructuredOutputError

/// Errors related to structured output processing.
///
/// For schema validation errors, use `ValidationError` from the JSON package
/// (thrown by `JSONSchema.validate(_:)` and `JSON.validate(against:)`).
public enum StructuredOutputError: Error, LocalizedError {
    case invalidResponse(String)
    case decodingFailed(Error)
    case modelDoesNotSupportStructuredOutput(model: String, supportedModels: [String])
    case schemaRequired

    public var errorDescription: String? {
        switch self {
        case .invalidResponse(let message):
            return "Invalid structured response: \(message)"
        case .decodingFailed(let error):
            return "Failed to decode structured response: \(error.localizedDescription)"
        case .modelDoesNotSupportStructuredOutput(let model, let supportedModels):
            return "Model '\(model)' does not support structured output. Supported models: \(supportedModels.joined(separator: ", "))"
        case .schemaRequired:
            return "Response schema is required for structured output requests"
        }
    }
}

// MARK: - Backward Compatibility

/// Deprecated — use `ValidationError` from the JSON package instead.
extension StructuredOutputError {
    @available(*, deprecated, message: "Use ValidationError from the JSON package instead")
    public static func validationFailed(path: String, reason: String) -> StructuredOutputError {
        .invalidResponse("Validation failed at '\(path)': \(reason)")
    }
}
